name: Python application

on:
  push:
    branches: [ "unittesting" ]
  pull_request:
    branches: [ "unittesting" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m venv ~/gmxenv
        source ~/gmxenv/bin/activate
        pip install .
    - name: Test with unittest 
      run: |
        python -m unittest -v test/unit_tests.py

