#!/usr/bin/env python

#   // INITIAL DESCRIPTION //
"""Short Module Description; Reference To Readme"""

#   // MEATDATA //
__author__ = 'Florian Anders'
__date__ = '2024-01-09'

#   // IMPORTS //
import datetime

from gmx2qmmm.types import StrPath

#   // TODOS & NOTES //
#   TODO: This Is An Example To Do
#   NOTE: This Is An Example Note

#   // CLASS & METHOD DEFINITIONS //
class Logger():

    '''
    This Class Handles The Logging Of Important Information From gmx2qmmm
    '''

    @staticmethod
    def log(file: StrPath | None, message: str, mode="a") -> None:

        '''
        ------------------------------ \\
        EFFECT: \\
        --------------- \\
        Appends Information To The Specified Log File (file_log)\\
        ------------------------------ \\
        INPUT: \\
        --------------- \\
        file -> Path To A Logfile \\
        message -> Text To Be Written To The Logfile \\
        mode -> Passed On To `open` \\
        ------------------------------ \\
        RETURN: \\
        --------------- \\
        NONE \\
        ------------------------------ \\
        '''

        if file is None:
             return

        with open(file, mode=mode) as fp:
            fp.write('-' * 60 + '\n')
            fp.write(str(datetime.datetime.now()).split('.')[0] +'\n\n')
            fp.write(message + '\n')
            fp.write('-' * 60 + '\n\n')



class Output():

    '''
    This Class Handles The Output Files Generated By GMX2QMMM
    '''

    #   // INIT //
    def __init__(self) -> None:
        '''
        ------------------------------ \\
        EFFECT: \\
        --------------- \\
        NONE \\
        ------------------------------ \\
        INPUT: \\
        --------------- \\
        NONE \\
        ------------------------------ \\
        RETURN: \\
        --------------- \\
        NONE \\
        ------------------------------ \\
        '''

        self.energy_file = 'oenergy.txt'
        self.forces_file = 'oforces.txt'

        with open(self.energy_file, 'w') as oenergy:
             oenergy.write("Step\tQM\t\tMM\t\tLink\t\tTotal\n")

        with open(self.forces_file, 'w') as oforces:
             oforces.write('')

    def oenergy_append(self, int_step_current, qmenergy, mmenergy, linkcorrenergy, total_energy):

            '''
            ------------------------------ \\
            EFFECT: \\
            --------------- \\
            XX \\
            ------------------------------ \\
            INPUT: \\
            --------------- \\
            NONE \\
            ------------------------------ \\
            RETURN: \\
            --------------- \\
            NONE \\
            ------------------------------ \\
            '''

            with open(self.energy_file, 'a+') as oenergy:
                oenergy.write(f"{int_step_current}\t{qmenergy:.6f}\t{mmenergy:.6f}\t{linkcorrenergy:.6f}\t{total_energy:.6f}\n")

    def oforces_append(self, int_step_current, total_force):

            '''
            ------------------------------ \\
            EFFECT: \\
            --------------- \\
            XX \\
            ------------------------------ \\
            INPUT: \\
            --------------- \\
            NONE \\
            ------------------------------ \\
            RETURN: \\
            --------------- \\
            NONE \\
            ------------------------------ \\
            '''

            with open(self.forces_file, 'a+') as oforce:
                lines = []
                lines.append(f"Step {int_step_current}\n")

                for i in range(len(total_force)):
                    lines.append(f"{i + 1} {total_force[i][0]:.8f} {total_force[i][1]:.8f} {total_force[i][2]:.8f}\n")

                lines.append("\n")

                oforce.writelines(lines)