name: Python application

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniforge with Mamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Miniforge3
        miniforge-version: latest
        activate-environment: gmx2qmmm
        auto-activate-base: false
        use-mamba: true
    - name: Install dependencies
      run: |
        mamba env update -n gmx2qmmm --file env.yaml --prune
        conda run -n gmx2qmmm python -m pip install --upgrade pip
        conda run -n gmx2qmmm python -m pip install -e ".[test]"
        conda run -n gmx2qmmm python -c "import gmx2qmmm; print(gmx2qmmm.__version__)"
    - name: Lint with flake8
      run: |
        conda run -n gmx2qmmm python -m pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        conda run -n gmx2qmmm python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        conda run -n gmx2qmmm python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda run -n gmx2qmmm python -m pytest
